# GitHub Actions Workflow: Generate Snake Animation
# This workflow generates a snake animation for the GitHub profile and updates it every 12 hours.

name: Generate Snake Animation

on:
  # Schedule the workflow to run every 12 hours
  schedule: 
    - cron: "0 */12 * * *"

  # Allows for manual trigger of the workflow
  workflow_dispatch:

  # Run the workflow on push to the master branch
  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Generate the snake.svg file using the Platane/snk action
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: EbenBoakye
          outputs: dist/snake.svg?palette=github-light

      # Push the generated snake.svg file to the output branch
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
